version: "3"
services:
  api:
    build: .
    image: express-starter:0.0.0
    ports:
      - 8080:8080
    links:
      - mongo:mongo
  portainer:
    image: portainer/portainer:1.14.0
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:3.4.7
    ports:
      - 27017:27017
  mongoExpress:
    image: mongo-express:0.40.0
    links:
      - mongo:mongo
    ports:
      - 8082:8081
  redis:
    image: redis:4.0.1
    ports:
      - 6379:6379
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - 8081:8081
